name: Publish Python 🐍 distributions 📦 to PyPI on Release

on:
  release:
    types: [released]

jobs:
  build-n-publish:
    name: Build and publish Python 🐍 distributions 📦 to PyPI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Set up Python 3.12
      uses: actions/setup-python@v6
      with:
        python-version: 3.12

    - name: Set up uv
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true

    - name: Build library
      run: uv build


    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@v1.13.0
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}  