name: Publish Python 🐍 distributions 📦 to TestPyPI on Tag creation

on:
  release:
    types: [prereleased]

jobs:
  build-n-publish:
    name: Build and publish Python 🐍 distributions 📦 to TestPyPI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Set up uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Build library
        run: uv build

      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@v1.13.0
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/